# Generated by Django 6.0.5 on 2026-05-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_global_scopes(apps, schema_editor):
    Submission = apps.get_model("core", "Submission")
    SubmissionScope = apps.get_model("core", "SubmissionScope")
    Comment = apps.get_model("core", "Comment")
    CommentScope = apps.get_model("core", "CommentScope")
    SubmissionScope.objects.bulk_create(
        [SubmissionScope(submission_id=pk, kind="global")
         for pk in Submission.objects.values_list("pk", flat=True)]
    )
    CommentScope.objects.bulk_create(
        [CommentScope(comment_id=pk, kind="global")
         for pk in Comment.objects.values_list("pk", flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_save'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CommentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('global', 'Global'), ('community', 'Community'), ('private', 'Private')], max_length=16)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.comment')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.community')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('community__isnull', False), ('kind', 'community')), models.Q(models.Q(('kind', 'community'), _negated=True), ('community__isnull', True)), _connector='OR'), name='commentscope_community_when_community_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'community')), fields=('comment', 'community'), name='uniq_comment_community_scope'), models.UniqueConstraint(condition=models.Q(('kind', 'global')), fields=('comment',), name='uniq_comment_global_scope')],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('community', 'user'), name='uniq_community_membership')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('global', 'Global'), ('community', 'Community'), ('private', 'Private')], max_length=16)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.community')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.submission')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('community__isnull', False), ('kind', 'community')), models.Q(models.Q(('kind', 'community'), _negated=True), ('community__isnull', True)), _connector='OR'), name='submissionscope_community_when_community_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'community')), fields=('submission', 'community'), name='uniq_submission_community_scope'), models.UniqueConstraint(condition=models.Q(('kind', 'global')), fields=('submission',), name='uniq_submission_global_scope')],
            },
        ),
        migrations.RunPython(backfill_global_scopes, migrations.RunPython.noop),
    ]
