# Generated by Django 6.0.5 on 2026-05-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_communities_and_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_authors', to='core.author')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_authors', to='core.submission')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(related_name='submissions', through='core.SubmissionAuthor', to='core.author'),
        ),
        migrations.AddConstraint(
            model_name='submissionauthor',
            constraint=models.UniqueConstraint(fields=('submission', 'position'), name='uniq_submission_author_position'),
        ),
        migrations.AddConstraint(
            model_name='submissionauthor',
            constraint=models.UniqueConstraint(fields=('submission', 'author'), name='uniq_submission_author'),
        ),
    ]
