# Generated by Django 6.0.5 on 2026-05-16 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author_submission_doi_submission_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='color',
            field=models.CharField(default='#ff6600', help_text='Accent color shown on the community page and listings.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a 6-digit hex color like #ff6600.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
