# Generated by Django 6.0.5 on 2026-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_community_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
